### ISSUE TITLE
Don't enable highlight-parentheses in *Messages* to avoid Emacs bug

### ISSUE THREAD

**Issue by npostavs** [tsdh/highlight-parentheses.el#14]
The existence of overlays in `*Messages*` + overlays with modification-hooks + `message` calls can trigger [Emacs bug#21824](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21824).

This manifested as capitaomorte/yasnippet#607, I've added a workaround in yasnippet, but avoiding enabling highlight-parentheses-mode in `*Messages*` could help users of other packages that aren't aware of this.

**Comment by tsdh** [comment]
Done in a821a31.  Thanks for letting me know.
