### ISSUE TITLE
style like show-paren-mode?

### ISSUE THREAD

**Issue by mcandre** [tsdh/highlight-parentheses.el#15]
I love that highlight-parentheses allows me to control highlighting per-mode. However, I prefer the aesthetic that show-paren-mode provides (colorize only the parens level matching the parens under the cursor).

How can I configure highlight-parentheses to use a style closer to show-paren-mode?

**Comment by tsdh** [comment]
Hi @mcandre,

the minimum number of colors in `hl-paren-colors` (default: 4 colors) and `hl-paren-background-colors` (default: `nil`) dictate the number of highlighted paren levels.  So basically you just want to put `(setq hl-paren-colors '("red"))` (or whatever color you like) into your `~/.emacs` or do the same with `customize`.  Alternatively, customize both `hl-paren-colors` and `hl-paren-background-colors`.  The point is: both must define at most one color if you just want to highlight the current paren level.

**Comment by mcandre** [comment]
Thanks for the explanation. Would you mind posting a snippet for the lazy?

**Comment by tsdh** [comment]
@mcandre I already did.  Just putting, e.g.,

``` elisp
(setq hl-paren-colors '("firebrick1"))
```

somewhere into your `~/.emacs` should be enough to give you what you desire.
