### ISSUE TITLE
How to use underline instead change bracket color like sublime text

### ISSUE THREAD

**Issue by ooJerryLeeoo** [tsdh/highlight-parentheses.el#17]
How to use underline instead change bracket color like this
![screen shot 2017-02-01 at 10 53 55](https://cloud.githubusercontent.com/assets/20783502/22493777/224c5d64-e86d-11e6-9248-031bf1c267f1.png)

**Comment by tsdh** [comment]
See issue #9.  You can customize `hl-paren-face` to be underlined.  And if you want just underlined surrounding parens but no colors at all, set `hl-paren-colors` to something like `("black" "black" "black" "black" "black" "black" )` assuming your normal foreground color is black.
