### ISSUE TITLE
Dumping cl.el and convention touch-ups

### ISSUE THREAD

**Issue by integral-dw** [tsdh/highlight-parentheses.el#21]
Hi!
Really enjoy this package, and have been using it for several years now.
I was doing a little bit of cleaning up in my `.emacs` and randomly noticed Emacs nagging about `cl`.
I would be willing to put in the legwork to migrate this package to `cl-lib` and tidy up nitpicks from `package-lint`, `checkdoc` and `flycheck`.  Given that would introduce a breaking change (prefixes: `hl-paren-` -> `highlight-parentheses-`) I would bump the version number to `2.0` to alert users and sprinkle the file with `define-obsolete-function-alias` calls and so on.
Though before I'd get to work I would like to know if that PR would be welcome in the first place, given it is a rather intrusive change on my part.

**Comment by tsdh** [comment]
Indeed, it should use `cl-lib` and declare it as a dependency.  PR welcome!

WRT the prefix: I don't think the functions are used elsewhere, so I guess there's not need to provide aliases.  However, of course user customization must not break.  So we'd need many `define-obsolete-variable-alias` and `define-obsolete-face-alias`.  Not sure if there's a lot value in this exercise, though.

**Comment by integral-dw** [comment]
Great, I'll get to it sometime soon then.
> Not sure if there's a lot value in this exercise, though.

At the end of the day, it does very little except make the bad words go away.  But I find myself compelled to do it. :shrug:

**Comment by tsdh** [comment]
Closed by #22
