### ISSUE TITLE
[suggestion] Consider using an idle timer

### ISSUE THREAD

**Issue by Fuco1** [tsdh/highlight-parentheses.el#8]
I see you run the update after each command on the post-command-hook.  That is excessive as commands very rarely change the surrounding block.  `show-paren-mode` and similar modes usually call the update routine on an idle timer with a delay of 1/8th of a second or so, this makes it much more responsive (while it's a delay so small you won't notice during normal editing).  Setting the delay to 0 would return the behaviour to what you have now, so there's no downside.

This suggestion is related to https://github.com/Fuco1/smartparens/issues/366

Cheers.

**Comment by tsdh** [comment]
Yes, I confirm the slowdown.  It makes some large lisp buffers especially if there are very deeply nested forms, almost unscrollable.  I'll implement the suggestion and send you a pull request.

**Comment by tsdh** [comment]
Done by the merge of pull request #11.
